### ISSUE TITLE
Message received in wrong channel

### ISSUE THREAD

**Issue by FelberMartin** [ls1intum/artemis-android#115]
### Problem description
When receiving a new message while being in another chat in the android app, the new message is shown as belonging to the currently displayed chat. Even after reloading the message persists on the android app

In the following gif the android user is in the channel #tech-support and the webuser sends a message in channel #random. The android user sees the message in the #tech-support channel
![ArtemisChatReceiveMessageInWrongChannel](https://github.com/user-attachments/assets/57f9ac6f-652b-4283-a8f6-419a4e8c6bd2)

### Next steps
- Fix bug
- Write test to prevent this from happening in the future

**Comment by julian-wls** [comment]
I just tried to reproduce this. I think it only happens, when the message was sent in a public channel. I was unable to reproduce this by sending the message in private channels or as DM.
