### ISSUE TITLE
[BUG] App crashes when receiving answer message in a thread

### ISSUE THREAD

**Issue by julian-wls** [ls1intum/artemis-android#125]
### Describe the bug
When receiving a reply in any thread, the server tries to save the message in the database and crashes. The behavior was observed only partially, sometimes there were no issues saving the reply. This is probably connected to #62 and therefore PR #70

Stack trace:
`android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: metis_post_context.client_post_id, metis_post_context.course_id, metis_post_context.conversation_id, metis_post_context.type, metis_post_context.server_id (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY)`

**To Reproduce**
1. Open the App
2. Send a reply in any thread
3. The app might crash

**Comment by FelberMartin** [comment]
I tried to reproduce the bug on `develop` and TS1 with test users 1 and 20 in threads for course and dm channels but could not reproduce the crash.
I sent thread replies with user20 in a thread in the #random channel in the web app and tried user1 in the android app for:
- Being in the thread view
- in the #random channel
- in another channel
- in the conversation overview

None of the environments caused a crash.
@julian-wls  Can you try to reproduce the crash and give me some hints on what you did?

**Comment by FelberMartin** [comment]
Any updates on this @julian-wls ?
