### ISSUE TITLE
Profile Pictures: Followup

### ISSUE THREAD

**Issue by FelberMartin** [ls1intum/artemis-android#154]
After the basic functionality of profile pictures is merged (#111) take care of the following:

- Fix bug described below -> Not directly related to profile pictures -> extracted to #203 
- Click on profile picture shows popup dialog
  - This should only be possible on posts and conversation header imo
  - The "send message" button has been postponed, see #213 
- Show profile picture in ...
  - Conversation overview
  - Conversation header for DMs
  - User search (channel creation)
  - Conversation members
  - User settings screen
- Show in notifications -> this is not straight forward and seen as lower priority, see I extracted it into #216

This is the follow-up issue for #63.

**Comment by ahbitaqu** [comment]
Maybe we can also address this minor issue in this follow-up:
The profile pictures reload Everytime a message is sent, and while the message is sending they disappear completely
https://github.com/user-attachments/assets/91928886-4505-4afa-9a0e-4d0243fbcbd9

**Comment by julian-wls** [comment]
#178 introduced icons in the Account information section of the settings screen. Instead of displaying the person icon next to the full name we could add a profile picture here as well.
