### ISSUE TITLE
Change to Feedback data model

### ISSUE THREAD

**Issue by b-fein** [ls1intum/artemis-android#2]
In https://github.com/ls1intum/Artemis/pull/6386 the feedback is truncated if it is longer than the maximum length, and instead the client has to check for the `hasLongFeedback` and load the corresponding LongFeedbackText from `/api/results/{resultId}/feedbacks/{feedbackId}/long-feedback` if the user wants to see the full feedback.

This might affect how the app currently displays feedbacks (if it does).

**Comment by FelberMartin** [comment]
I just scanned through the code and as far as I can tell, feedback is (if so) only displayed through a WebView.

Considering that, i close the issue as invalid

**Comment by FelberMartin** [comment]
I just scanned through the code and as far as I can tell, feedback is (if so) only displayed through a WebView.

Considering that, i close the issue as won't fix
