### ISSUE TITLE
`Communication`: Improve messaging notifications and settings

### ISSUE THREAD

**Issue by nityanandaz** [ls1intum/artemis-android#27]
https://github.com/ls1intum/Artemis/pull/7377 adds three new kinds of notifications:

- NOTIFICATION__EXAM_NOTIFICATION__NEW_EXAM_POST
- NOTIFICATION__EXAM_NOTIFICATION__NEW_REPLY_FOR_EXAM_POST
- NOTIFICATION__USER_NOTIFICATION__USER_MENTION

**Comment by FelberMartin** [comment]
These notifications were included in #55 

Closing the issue as done
