### ISSUE TITLE
`Communication`: Subscribe to course-wide channels

### ISSUE THREAD

**Issue by nityanandaz** [ls1intum/artemis-android#29]
https://github.com/ls1intum/Artemis/pull/7437 updates WebSocket topics.

> For course-wide channels, the client no longer subscribes to conversation-specific topics, but to course-wide topic `/topic/metis/courses/:courseId`, to be able to receive updates from multiple channels. The server sends WebSocket messages for new messages or message updates to this topic.

---

Copy of https://github.com/ls1intum/artemis-ios/issues/63

**Comment by FelberMartin** [comment]
Addressed in https://github.com/ls1intum/artemis-android/pull/30
