### ISSUE TITLE
`Communication`: Problem fetching updated message after editing in conversations

### ISSUE THREAD

**Issue by julian-wls** [ls1intum/artemis-android#60]
### Problem
After editing a message or resolving a message the app pushes the changes to the artemis API. However the changes are not reflected in the UI. Updating the content of a message, for example does not trigger a reload of the UI to show the new content. See this [discussion](https://github.com/ls1intum/artemis-android/pull/59#discussion_r1807272998) in PR #59 for more information.

### Suggestions
There seems to be a problem with the websocket connection as updates are not sent to the client after making changes to posts. A deeper look into the websocket might be necassary.

**Comment by FelberMartin** [comment]
I don't know whether this has been the case from the beginning, but I can no longer observe the problem in public channels, but eg for group chats and direct messages
