### ISSUE TITLE
Re-Enabling EdgeToEdge

### ISSUE THREAD

**Issue by FelberMartin** [ls1intum/artemis-android#68]
I found that with `enableEdgeToEdge()` introduced in #43 the keyboard was covering the message TextField in the Chat UI (see screenshot below).
![image](https://github.com/user-attachments/assets/4d182dd2-5507-49d5-bbd7-ac4090704daf)

The same also holds for other TextFields. Eg when tapping on the Search in the ConversationOverview, the Keyboard covers the FAB-Button (for creating new chats). Without the `enableEdgeToEdge()` this does not happen.

Therefore I temporally removed this line from `main`. 

### Next Steps
- Confirm whether this is not just an issue on the emulator but also on the physical device.
- Resolve the issue. I found that by adding `Modifer.imePadding()` eg to line 320 of `CourseUiScreen.kt` does remove the problem. However, I am not sure what the best approach is to fix this consistently. There are probably much more TextFields that cause the same problem and adding the Modifier to each and every Scaffold does not feel right imo

**Comment by julian-wls** [comment]
I think we need to use insets to handle any overlapping as described [here](https://developer.android.com/develop/ui/views/layout/edge-to-edge#handle-overlaps). I think using `Modifier.imePadding()` is the correct way even though it feels a bit weird, but [the documentation](https://developer.android.com/develop/ui/compose/layouts/insets#inset-consumption) handles it that way. I'll take a deeper look in the next days.
