### ISSUE TITLE
Support user mentions

### ISSUE THREAD

**Issue by lennart-keller** [ls1intum/artemis-android#8]
With https://github.com/ls1intum/Artemis/pull/7206, the web client supports parsing user mentions of the format `[user]Full Name(login)[/user]` within messages, posts, and replies. 

The app needs to support this format as well to display messages/posts/replies containing user mentions correctly.

In the web client, by clicking on a user mention, the user automatically navigates to a new or existing one-to-one chat with the mentioned user. This behavior would also be nice to have in the app.

Additionally, with https://github.com/ls1intum/Artemis/pull/7286, there is a new button in the message/post/reply editor, which inserts an @ sign and opens a small pop-up window, listing 10 possible course members to mention. The list updates, if the user types a name after the @ sign. For this, the endpoint GET /api/courses/:courseId/members/search?loginOrName=name is called.
The pop-up can also be opened by just typing an @ sign. 

A similar feature for the app would be necessary for users to type in user mentions.

**Comment by TimOrtel** [comment]
Closed by https://github.com/ls1intum/artemis-android/pull/14 and https://github.com/ls1intum/artemis-android/pull/22
